### ISSUE TITLE
Image doesn't show alias section

### ISSUE THREAD

**Issue by VictorVelarde** [zjhch123/react-map-gl-demo-with-create-react-app#1]
Hi @zjhch123 
I just wanted to let you know that the last image doesn't show the alias section, although I followed your instructions and it worked like a charm, thx!

**Comment by zjhch123** [comment]
@VictorVelarde emmmm...
which image...? i can't find it...😅😅

**Comment by VictorVelarde** [comment]
Hi,
This one! https://camo.githubusercontent.com/b2d38a9c341ff1e16ade3cb3182e88d7c57045e1/68747470733a2f2f696d6167652e6864757a706c75732e78797a2f696d6167652f313530303338333334343736362e706e67

**Comment by zjhch123** [comment]
fixed~☺
